# Generated by Django 4.0.7 on 2022-09-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(choices=[('n.', 'Noun'), ('pro.', 'Pronoun'), ('v.', 'Verb'), ('adj.', 'Adjective'), ('adv.', 'Adverb'), ('prep.', 'Preposition'), ('conj.', 'Conjunction'), ('int.', 'Interjection')], max_length=255)),
                ('definition', models.TextField(max_length=255, verbose_name='word')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'part_of_speech', 'created_user'), name='word_unique'),
        ),
    ]
